import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="Churn Risk Dashboard", layout="wide")
st.title("🔄 User Lifecycle Stagnation Dashboard")
st.markdown("Automated ELT Pipeline Output: Identifying High-Risk Churn Candidates")

# 2. Load the Data
@st.cache_data
def load_data():
    # Reads the CSV generated by your MySQL analysis
    return pd.read_csv('final_segmentation.csv')

try:
    df = load_data()
    
    # 3. Top Level KPIs
    st.markdown("### 📊 Key Performance Indicators")
    col1, col2, col3 = st.columns(3)
    
    high_risk_df = df[df['status'] == 'High-Risk Stagnant']
    capital_at_risk = high_risk_df['total_stored_value'].sum()
    
    col1.metric("Total Users Analyzed", len(df))
    col2.metric("High-Risk Stagnant Users", len(high_risk_df))
    col3.metric("Total Capital at Risk", f"${capital_at_risk:,.2f}")
    
    st.divider()

    # 4. Interactive Charts
    col_chart1, col_chart2 = st.columns(2)
    
    with col_chart1:
        st.subheader("User Segmentation")
        # Bar chart showing the count of each status
        status_counts = df['status'].value_counts().reset_index()
        status_counts.columns = ['Status', 'User Count']
        fig_bar = px.bar(status_counts, x='Status', y='User Count', color='Status', 
                         color_discrete_sequence=px.colors.qualitative.Pastel)
        st.plotly_chart(fig_bar, use_container_width=True)

    with col_chart2:
        st.subheader("Value-Exchange Latency")
        # Scatter plot showing risk distribution
        fig_scatter = px.scatter(df, x='days_since_last_use', y='total_stored_value', 
                                 color='status', hover_data=['user_id'],
                                 labels={'days_since_last_use': 'Days Since Last Use', 'total_stored_value': 'Stored Value ($)'},
                                 color_discrete_sequence=px.colors.qualitative.Pastel)
        st.plotly_chart(fig_scatter, use_container_width=True)

    # 5. Raw Data Explorer
    st.subheader("High-Risk User Roster")
    st.markdown("List of users requiring immediate re-engagement campaigns.")
    st.dataframe(high_risk_df[['user_id', 'days_since_last_use', 'total_stored_value']].sort_values(by='total_stored_value', ascending=False), use_container_width=True)

except FileNotFoundError:
    st.error("Error: 'final_segmentation.csv' not found. Please run the ELT pipeline (01, 02, 03) first.")