import streamlit as st
import pandas as pd
import plotly.express as px

# =====================================================================
# ORIGINAL DATA PIPELINE (COMMENTED OUT FOR CLOUD DEPLOYMENT)
# 
# The following code represents the backend ELT pipeline used to 
# generate the 'final_segmentation.csv' file. It connects to the local 
# MySQL database, executes Window Functions to calculate value-exchange 
# latency, and segments user churn risk.
# =====================================================================
# from sqlalchemy import create_engine
#
# # 1. Connect to local MySQL database
# engine = create_engine('mysql+mysqlconnector://user:password@localhost/db_name')
#
# # 2. Execute SQL Window Functions for latency and churn risk
# query = """
#     SELECT 
#         user_id,
#         MAX(transaction_date) as last_transaction,
#         DATEDIFF(CURRENT_DATE, MAX(transaction_date)) as value_exchange_latency,
#         SUM(capital_balance) as idle_capital,
#         CASE 
#             WHEN DATEDIFF(CURRENT_DATE, MAX(transaction_date)) > 30 THEN 'High Risk'
#             WHEN DATEDIFF(CURRENT_DATE, MAX(transaction_date)) > 15 THEN 'Medium Risk'
#             ELSE 'Low Risk'
#         END as churn_risk_segment
#     FROM user_ledgers
#     GROUP BY user_id
# """
#
# # 3. Load into DataFrame and export to static CSV for Streamlit Cloud
# df_live = pd.read_sql(query, engine)
# df_live.to_csv('final_segmentation.csv', index=False)
# =====================================================================


# --- 1. PAGE SETUP ---
st.set_page_config(page_title="Churn Risk Dashboard", page_icon="🔄", layout="wide")

st.title("🔄 User Lifecycle Stagnation & Churn Analysis")
st.markdown("Isolating high-risk users based on Value-Exchange Latency and Idle Capital.")
st.divider()

# --- 2. DATA LOADING (The CSV Fix) ---
@st.cache_data
def load_data():
    # Reading from the static file generated by the pipeline above
    df = pd.read_csv('final_segmentation.csv')
    return df

# --- 3. DASHBOARD DISPLAY ---
try:
    # Load the data
    df = load_data()
    
    # Display top-level metrics
    st.subheader("High-Risk User Roster")
    
    # Displays your fully transformed data table
    st.dataframe(df, use_container_width=True)
    

except FileNotFoundError:
    st.error("🚨 Error: Could not find 'final_segmentation.csv'. Please ensure it is uploaded to the GitHub repository.")
except Exception as e:
    st.error(f"🚨 An error occurred: {e}")
